name: ci-nextjs-application-template
on:
  push:
    branches: [main, master, issue-24]
  pull_request:
    branches: [main, master]
env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/panic?schema=public
  NEXTAUTH_SECRET: secret
  NEXTAUTH_URL: http://localhost:3000
  POSTGRES_HOST: postgres
jobs:
  test:
    services:
      postgres:
        image: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: panic
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Migrate and seed database
        run: |
          npx prisma migrate dev
          npx prisma db seed
      - name: Install Playwright and run tests
        run: |
          npx playwright install --with-deps
          DEBUG=pw:api npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
